name: Deploy Aitrix React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Upload build folder to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: "dist"
        target: "/var/www/aitrix_tmp"

    - name: Run deploy commands on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          rm -rf /var/www/aitrix/*
          mv /var/www/aitrix_tmp/* /var/www/aitrix/
          rm -rf /var/www/aitrix_tmp
          chown -R www-data:www-data /var/www/aitrix
          chmod -R 755 /var/www/aitrix
          nginx -t && systemctl reload nginx
