name: Deploy Aitrix React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Add VPS to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: "dist/public/*"
        target: "/var/www/aitrix"
