name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
        
    - name: Add server to known hosts
      run: |
        echo "${{ secrets.VPS_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        
    - name: Deploy to VPS
      run: |
        # Create deployment directory on server
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "mkdir -p /var/www/aitrix-website"
        
        # Copy files to server
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/var/www/aitrix-website/
        
        # Set proper permissions
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "chmod -R 755 /var/www/aitrix-website"
        
        # Restart web server (adjust based on your setup - nginx, apache, etc.)
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "sudo systemctl reload nginx || sudo systemctl reload apache2 || true"
        
    - name: Deployment Status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Website should be available at: http://${{ secrets.VPS_HOST }}"
